
[
    {
        "img": "https://i.ibb.co/f183SSQ/about.jpg",
        "name": "Raju Talukder",
        "employeeType": "Employee",
        "email": "rajutalukdar2769@gmail.com",
        "department": "Team Leader",
        "designation": "Web Developer",
        "joiningDate": "01 Jul 2020",
        "DOB": "05 Dec 1979",
        "maritalStatus": "Unmarried",
        "gender": "Male",
        "salary": 30000,
        "address": "Faridpur, Dhaka",
        "nationality": "Bangladeshi",
        "phone": "01306-772769",
        "EmergencyContactDetails": "7894561235",
        "Experience": "0 years 5 months and 24 days",
        "Status": "Active"
    },
    {
        "img": "https://i.ibb.co/qCf3n1W/11775.png",
        "name": "Ishtiaq Robin",
        "employeeType": "Employee",
        "email": "robin.pass36@gmail.com",
        "department": "Web Developer",
        "designation": "Web Developer",
        "joiningDate": "01 Jul 2020",
        "DOB": "05 Dec 1979",
        "maritalStatus": "Unmarried",
        "gender": "Male",
        "salary": 20000,
        "address": "Faridpur, Dhaka",
        "nationality": "Bangladeshi",
        "phone": "01762-627422",
        "EmergencyContactDetails": "7894561235",
        "Experience": "0 years 5 months and 24 days",
        "Status": "Active"
    },
    {
        "img": "https://smarthr.dreamguystech.com/tailwind/template/src/images/profile",
        "name": "Sumon Kaysar",
        "employeeType": "Employee",
        "email": "hemon.hasan123@gmail.com",
        "department": "Design",
        "designation": "Web Developer",
        "joiningDate": "01 Jul 2020",
        "DOB": "05 Dec 1979",
        "maritalStatus": "Unmarried",
        "gender": "Male",
        "salary": 18000,
        "address": "Panchdona, Narsingdi",
        "nationality": "Bangladeshi",
        "phone": "01828-008748",
        "EmergencyContactDetails": "7894561235",
        "Experience": "0 years 5 months and 24 days",
        "Status": "Active"
    },
    {
        "img": "https://smarthr.dreamguystech.com/tailwind/template/src/images/profile",
        "name": "Jabed",
        "employeeType": "Employee",
        "email": "hemon.hasan123@gmail.com",
        "department": "Android Developer",
        "designation": "Web Developer",
        "joiningDate": "01 Jul 2020",
        "DOB": "05 Dec 1979",
        "maritalStatus": "Unmarried",
        "gender": "Male",
        "salary": 22000,
        "address": "Panchdona, Narsingdi",
        "nationality": "Bangladeshi",
        "phone": "01828-008748",
        "EmergencyContactDetails": "7894561235",
        "Experience": "0 years 5 months and 24 days",
        "Status": "Active"
    },
    {
        "img": "https://i.ibb.co/GnjtCpf/1670525634938.jpg",
        "name": "Anaf Sagor",
        "employeeType": "Employee",
        "email": "ahnafsagor12@gmail.com",
        "department": "Web Developer",
        "designation": "Web Developer",
        "joiningDate": "01 Jul 2020",
        "DOB": "05 Dec 1979",
        "maritalStatus": "Unmarried",
        "gender": "Male",
        "salary": 18000,
        "address": "Panchdona, Rongpur",
        "nationality": "Bangladeshi",
        "phone": "01997-582473",
        "EmergencyContactDetails": "7894561235",
        "Experience": "0 years 5 months and 24 days",
        "Status": "Active"
    },
    {
        "img": "https://i.ibb.co/dMH27DW/IMG-20220603-205920-copy.png",
        "name": "Md. Rofiqul Islam",
        "employeeType": "Employee",
        "email": "ahnafsagor12@gmail.com",
        "department": "Web Developer",
        "designation": "Web Developer",
        "joiningDate": "01 Jul 2020",
        "DOB": "05 Dec 1979",
        "maritalStatus": "Unmarried",
        "gender": "Male",
        "salary": 21000,
        "address": "Kaligonj, Satkhira",
        "nationality": "Bangladeshi",
        "phone": "01926-881485",
        "EmergencyContactDetails": "7894561235",
        "Experience": "0 years 5 months and 24 days",
        "Status": "Active"
    },
    {"_id":{"$oid":"63ebc24706057fbc6ea3d0f4"},"profile":{"email":"robin.pass36@gmail.com","uid":"ATrEsIG8NIND3m8T4TNpXVNOMt93","personal_info":{"passport_no":"9876543210","tel":"+880 1762-627422","nationality":"Bangladeshi","religion":"Islam","marital_status":"Unmarried","employment_of_spouse":"No","no_of_children":"4","name":"Personal Information"},"emergency_contact":{"primary":"John Doe","relationship":"Brother","secondary":"Karen Wills","phone":"+880 1646-202917","name":"Emergency Contact"},"bank_information":{"bank_name":"John ICC Bank","bank_account_no":"159843014641","secondary":"Karen Wills","relationship":"Brother"},"education_information":{"ug":"Bsc Computer Science","ug_year":"2000 - 2003","pg":"Msc Computer Science","pg_year":"2000 - 2003","name":"Education Informations"},"experience":{"experience_1":"Web Designer at Zen Corporation","experience_1_join":"Jan 2013 - Present (5 years 2 months)","experience_2":"Web Designer at Ron-tech","experience_2_join":"Jan 2013 - Present (5 years 2 months)","experience_3":"Web Designer at Dale Technology","experience_3_join":"Jan 2013 - Present (5 years 2 months)","name":"Experience"}},"img":"https://i.ibb.co/fHWpw4s/11775.png","name":"Ishtiaq Robin","employeeType":"Employee","email":"robin.pass36@gmail.com","department":"Web Developer","designation":"Web ","joiningDate":"01 Jul 2020","DOB":"01 Dec 2002","maritalStatus":"Unmarried","gender":"Male","salary":"20000","address":"Faridur Sadar, Faridpur.","nationality":"Bangladeshi","phone":"+8801762627422","EmergencyContactDetails":"7894561235","Experience":"0 years 5 months and 24 days","Status":"Active","postTime":"1/31/2023, 8:07:56 PM","employeeId":"pt-007262","children":"4","marital_status":"Unmarried","passport_no":"987654321012","religion":"Islam","spouse":"No","tel":"+880 1762-627422"," experience_2":"Web Designer at Ron-tech","bank_account_no":"05151654215","bank_name":"John ICC Bank","employment_of_spouse":"No","experience_1":"Web Designer at Zen Corporation","experience_1_join":"Jan 2013 - Present (5 years 2 months)","experience_2_join":"Jan 2013 - Present (5 years 2 months)","experience_3":"Web Designer at Dale Technology","experience_3_join":"Jan 2013 - Present (5 years 2 months)","no_of_children":"02","pg":"Msc Computer Science","pg_year":"2000 - 2003","primary":"Jhon Deo","relationship":"Brother","secondary":"Karen Wills","secondary_phone":"+548451514544","ug":"Bsc Computer Science","ug_year":"2000 - 2003"}
]