
[
    {
        "img": "https://i.ibb.co/f183SSQ/about.jpg",
        "name": "Raju Talukder",
        "employeeType": "Employee",
        "email": "rajutalukdar2769@gmail.com",
        "department": "Team Leader",
        "designation": "Web Developer",
        "joiningDate": "01 Jul 2020",
        "DOB": "05 Dec 1979",
        "maritalStatus": "Unmarried",
        "gender": "Male",
        "salary": 30000,
        "address": "Faridpur, Dhaka",
        "nationality": "Bangladeshi",
        "phone": "01306-772769",
        "EmergencyContactDetails": "7894561235",
        "Experience": "0 years 5 months and 24 days",
        "Status": "Active"
    },
    {
        "img": "https://i.ibb.co/qCf3n1W/11775.png",
        "name": "Ishtiaq Robin",
        "employeeType": "Employee",
        "email": "robin.pass36@gmail.com",
        "department": "Web Developer",
        "designation": "Web Developer",
        "joiningDate": "01 Jul 2020",
        "DOB": "05 Dec 1979",
        "maritalStatus": "Unmarried",
        "gender": "Male",
        "salary": 20000,
        "address": "Faridpur, Dhaka",
        "nationality": "Bangladeshi",
        "phone": "01762-627422",
        "EmergencyContactDetails": "7894561235",
        "Experience": "0 years 5 months and 24 days",
        "Status": "Active"
    },
    {
        "img": "https://smarthr.dreamguystech.com/tailwind/template/src/images/profile",
        "name": "Sumon Kaysar",
        "employeeType": "Employee",
        "email": "hemon.hasan123@gmail.com",
        "department": "Design",
        "designation": "Web Developer",
        "joiningDate": "01 Jul 2020",
        "DOB": "05 Dec 1979",
        "maritalStatus": "Unmarried",
        "gender": "Male",
        "salary": 18000,
        "address": "Panchdona, Narsingdi",
        "nationality": "Bangladeshi",
        "phone": "01828-008748",
        "EmergencyContactDetails": "7894561235",
        "Experience": "0 years 5 months and 24 days",
        "Status": "Active"
    },
    {
        "img": "https://smarthr.dreamguystech.com/tailwind/template/src/images/profile",
        "name": "Jabed",
        "employeeType": "Employee",
        "email": "hemon.hasan123@gmail.com",
        "department": "Android Developer",
        "designation": "Web Developer",
        "joiningDate": "01 Jul 2020",
        "DOB": "05 Dec 1979",
        "maritalStatus": "Unmarried",
        "gender": "Male",
        "salary": 22000,
        "address": "Panchdona, Narsingdi",
        "nationality": "Bangladeshi",
        "phone": "01828-008748",
        "EmergencyContactDetails": "7894561235",
        "Experience": "0 years 5 months and 24 days",
        "Status": "Active"
    },
    {
        "img": "https://i.ibb.co/GnjtCpf/1670525634938.jpg",
        "name": "Anaf Sagor",
        "employeeType": "Employee",
        "email": "ahnafsagor12@gmail.com",
        "department": "Web Developer",
        "designation": "Web Developer",
        "joiningDate": "01 Jul 2020",
        "DOB": "05 Dec 1979",
        "maritalStatus": "Unmarried",
        "gender": "Male",
        "salary": 18000,
        "address": "Panchdona, Rongpur",
        "nationality": "Bangladeshi",
        "phone": "01997-582473",
        "EmergencyContactDetails": "7894561235",
        "Experience": "0 years 5 months and 24 days",
        "Status": "Active"
    },
    {
        "img": "https://i.ibb.co/dMH27DW/IMG-20220603-205920-copy.png",
        "name": "Md. Rofiqul Islam",
        "employeeType": "Employee",
        "email": "ahnafsagor12@gmail.com",
        "department": "Web Developer",
        "designation": "Web Developer",
        "joiningDate": "01 Jul 2020",
        "DOB": "05 Dec 1979",
        "maritalStatus": "Unmarried",
        "gender": "Male",
        "salary": 21000,
        "address": "Kaligonj, Satkhira",
        "nationality": "Bangladeshi",
        "phone": "01926-881485",
        "EmergencyContactDetails": "7894561235",
        "Experience": "0 years 5 months and 24 days",
        "Status": "Active"
    }
]